"""AWS deployment ARTIFACT GENERATOR (CONTRACTS.md §9).

This module does NOT provision AWS. It generates a CloudFormation template
(IaC artifact) that the operator applies themselves, e.g.:

    aws cloudformation deploy \
        --template-file deploy-out/aws-stack.yaml \
        --stack-name authy-prod \
        --parameter-overrides Env=production InstanceType=t3.medium

``health_check`` validates the generated template structure and returns
``False`` when nothing valid has been built — it never returns an
unconditional ``True``.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, Optional

__all__ = ["AWSDeploymentEngine"]


class AWSDeploymentEngine:
    """Builds CloudFormation artifacts for the Authy stack.

    Named "engine" for backwards compatibility; it is a template builder —
    all real provisioning happens when the operator applies the artifact.
    """

    def __init__(self, region: str = "us-east-1") -> None:
        self.region = region
        self._template: Optional[Dict[str, Any]] = None

    def build_template(
        self,
        *,
        env: str = "production",
        instance_type: str = "t3.medium",
        app_port: int = 8000,
    ) -> Dict[str, Any]:
        """Build (and cache) the CloudFormation template dict."""
        self._template = {
            "AWSTemplateFormatVersion": "2010-09-09",
            "Description": (
                f"Authy application stack ({env}) — generated by authy deploy aws. "
                "Review before applying; parameters must be supplied at deploy time."
            ),
            "Parameters": {
                "Env": {
                    "Type": "String",
                    "Default": env,
                    "AllowedValues": ["development", "staging", "production"],
                },
                "InstanceType": {"Type": "String", "Default": instance_type},
                "VpcId": {"Type": "AWS::EC2::VPC::Id", "Description": "Target VPC"},
                "LatestAmiId": {
                    "Type": "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>",
                    "Default": "/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64",
                },
            },
            "Resources": {
                "AppSecurityGroup": {
                    "Type": "AWS::EC2::SecurityGroup",
                    "Properties": {
                        "GroupDescription": "Authy app security group",
                        "VpcId": {"Ref": "VpcId"},
                        "SecurityGroupIngress": [
                            {
                                "IpProtocol": "tcp",
                                "FromPort": app_port,
                                "ToPort": app_port,
                                "CidrIp": "0.0.0.0/0",
                                "Description": "Application port",
                            }
                        ],
                    },
                },
                "AppInstance": {
                    "Type": "AWS::EC2::Instance",
                    "Properties": {
                        "ImageId": {"Ref": "LatestAmiId"},
                        "InstanceType": {"Ref": "InstanceType"},
                        "SecurityGroupIds": [
                            {"Fn::GetAtt": ["AppSecurityGroup", "GroupId"]}
                        ],
                        "Tags": [
                            {"Key": "authy:env", "Value": {"Ref": "Env"}},
                            {"Key": "Name", "Value": {"Fn::Sub": "authy-${Env}"}},
                        ],
                    },
                },
            },
            "Outputs": {
                "InstanceId": {
                    "Value": {"Ref": "AppInstance"},
                    "Description": "EC2 instance id (known only after deploy)",
                }
            },
        }
        return self._template

    def write(self, output_path: Path) -> Path:
        """Serialize the template to ``output_path`` as YAML."""
        if self._template is None:
            self.build_template()
        try:
            import yaml
        except ImportError as exc:  # honest failure — never write invalid YAML by hand
            raise RuntimeError(
                "PyYAML is required to write CloudFormation artifacts "
                "(pip install pyyaml)"
            ) from exc
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as handle:
            yaml.safe_dump(self._template, handle, sort_keys=False)
        return output_path

    def health_check(self) -> bool:
        """True only when a structurally valid template has been built."""
        if not isinstance(self._template, dict):
            return False
        if self._template.get("AWSTemplateFormatVersion") != "2010-09-09":
            return False
        resources = self._template.get("Resources")
        return bool(resources) and all(
            isinstance(res, dict) and res.get("Type") for res in resources.values()
        )
