"""``authy deploy`` — honest multi-target deployment (CONTRACTS.md §9).

- ``docker``: REAL — detects the docker CLI, builds the image from the
  project Dockerfile (generating a minimal one when missing), and optionally
  runs the container. Errors from docker are surfaced verbatim.
- ``aws`` / ``gcp`` / ``azure`` / ``kubernetes``: generate IaC artifacts
  (CloudFormation YAML, compose YAML, Kubernetes manifests) into
  ``./deploy-out/`` and print EXACTLY that. No cloud API calls, no fake
  resource ids, no fake "deployed" output.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path
from typing import List, Optional

import click
from rich.console import Console

console = Console()

DEPLOY_OUT_DIR = Path("deploy-out")

DEFAULT_DOCKERFILE = """\
# Generated by `authy deploy docker` — adjust to your application layout.
FROM python:3.12-slim

WORKDIR /app
COPY requirements.txt* ./
RUN pip install --no-cache-dir -r requirements.txt || true
COPY . .

EXPOSE 8000
CMD ["python", "-m", "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
"""


def _write_artifact(path: Path, content: str) -> Path:
    """Write one artifact under ./deploy-out/."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return path


@click.group(name="deploy")
def deploy_cmd():
    """Deploy Authy (docker for real; cloud targets generate IaC artifacts)."""


# ---------------------------------------------------------------------------
# docker — real build/run
# ---------------------------------------------------------------------------

@deploy_cmd.command("docker")
@click.option("--tag", "-t", default="authy-app:latest", show_default=True, help="Image tag")
@click.option("--run", "run_container", is_flag=True, help="Run the container after build")
@click.option("--port", "-p", default=8000, show_default=True, help="Host port when --run")
@click.option("--dockerfile", default="Dockerfile", show_default=True, help="Dockerfile path")
def docker(tag: str, run_container: bool, port: int, dockerfile: str):
    """Build (and optionally run) a Docker image using the local docker CLI."""
    docker_bin = shutil.which("docker")
    if docker_bin is None:
        console.print(
            "[red]✗ docker CLI not found on PATH. Install Docker to use this "
            "command — nothing was built.[/red]"
        )
        raise click.exceptions.Exit(1)

    dockerfile_path = Path(dockerfile)
    if not dockerfile_path.exists():
        dockerfile_path.write_text(DEFAULT_DOCKERFILE, encoding="utf-8")
        console.print(f"[yellow]No Dockerfile found — generated {dockerfile_path}[/yellow]")

    console.print(f"[blue]Building image {tag} from {dockerfile_path} …[/blue]")
    build = subprocess.run(
        [docker_bin, "build", "-t", tag, "-f", str(dockerfile_path), "."],
        capture_output=True,
        text=True,
    )
    if build.returncode != 0:
        console.print(f"[red]✗ docker build failed (exit {build.returncode}):[/red]")
        console.print(build.stderr.strip() or build.stdout.strip())
        raise click.exceptions.Exit(build.returncode)
    console.print(f"[green]✓ Built image {tag}[/green]")

    if not run_container:
        console.print("[dim]Skipping container start (pass --run to start it).[/dim]")
        return

    container_name = tag.replace(":", "-").replace("/", "-") + "-dev"
    console.print(f"[blue]Running container {container_name} on port {port} …[/blue]")
    run = subprocess.run(
        [
            docker_bin, "run", "--rm", "-d",
            "--name", container_name,
            "-p", f"{port}:8000",
            tag,
        ],
        capture_output=True,
        text=True,
    )
    if run.returncode != 0:
        console.print(f"[red]✗ docker run failed (exit {run.returncode}):[/red]")
        console.print(run.stderr.strip() or run.stdout.strip())
        raise click.exceptions.Exit(run.returncode)
    console.print(
        f"[green]✓ Container {container_name} started "
        f"(id={run.stdout.strip()[:12]}, port {port})[/green]"
    )


# ---------------------------------------------------------------------------
# IaC artifact generators (no cloud calls)
# ---------------------------------------------------------------------------

@deploy_cmd.command("aws")
@click.option("--env", "-e", default="production", show_default=True)
@click.option("--region", "-r", default="us-east-1", show_default=True)
@click.option("--instance-type", default="t3.medium", show_default=True)
def aws(env: str, region: str, instance_type: str):
    """Generate a CloudFormation artifact into ./deploy-out/ (no AWS calls)."""
    from ..deploy.aws_engine import AWSDeploymentEngine

    engine = AWSDeploymentEngine(region=region)
    engine.build_template(env=env, instance_type=instance_type)
    if not engine.health_check():
        console.print("[red]✗ Generated template failed internal validation[/red]")
        raise click.exceptions.Exit(1)

    out = engine.write(DEPLOY_OUT_DIR / "aws-stack.yaml")
    readme = _write_artifact(
        DEPLOY_OUT_DIR / "README.md",
        "# deploy-out\n\nGenerated IaC artifacts. Review them, then apply manually:\n\n"
        "## AWS\n```bash\naws cloudformation deploy "
        f"--template-file {out} --stack-name authy-{env} "
        "--parameter-overrides Env={env} InstanceType={instance_type} "
        "VpcId=<your-vpc-id>\n```\n\n"
        "Nothing has been deployed by the CLI; resource ids only exist after "
        "you apply the template.\n",
    )
    console.print(f"[green]✓ Generated CloudFormation artifact:[/green] {out}")
    console.print(f"[dim]Also wrote {readme}. No AWS resources were created.[/dim]")


@deploy_cmd.command("gcp")
@click.option("--project-id", required=True, help="GCP project id (recorded in the artifact)")
@click.option("--region", "-r", default="us-central1", show_default=True)
@click.option("--image", default="authy-app:latest", show_default=True)
def gcp(project_id: str, region: str, image: str):
    """Generate a compose artifact for GCP into ./deploy-out/ (no GCP calls)."""
    try:
        import yaml
    except ImportError:
        console.print("[red]✗ PyYAML is required to generate artifacts[/red]")
        raise click.exceptions.Exit(1)

    compose = {
        "version": "3.9",
        "x-generated-by": "authy deploy gcp (artifact only — not deployed)",
        "x-gcp": {"project_id": project_id, "region": region},
        "services": {
            "authy": {
                "image": image,
                "ports": ["8000:8000"],
                "restart": "unless-stopped",
            }
        },
    }
    out = _write_artifact(
        DEPLOY_OUT_DIR / "gcp-compose.yaml",
        yaml.safe_dump(compose, sort_keys=False),
    )
    console.print(f"[green]✓ Generated compose artifact:[/green] {out}")
    console.print(
        "[dim]Deploy it yourself, e.g. `gcloud run deploy` with a container "
        "image or `docker compose -f "
        f"{out} up`. No GCP resources were created.[/dim]"
    )


@deploy_cmd.command("azure")
@click.option("--resource-group", required=True, help="Recorded in the artifact")
@click.option("--location", "-l", default="eastus", show_default=True)
@click.option("--image", default="authy-app:latest", show_default=True)
def azure(resource_group: str, location: str, image: str):
    """Generate a compose artifact for Azure into ./deploy-out/ (no Azure calls)."""
    try:
        import yaml
    except ImportError:
        console.print("[red]✗ PyYAML is required to generate artifacts[/red]")
        raise click.exceptions.Exit(1)

    compose = {
        "version": "3.9",
        "x-generated-by": "authy deploy azure (artifact only — not deployed)",
        "x-azure": {"resource_group": resource_group, "location": location},
        "services": {
            "authy": {
                "image": image,
                "ports": ["8000:8000"],
                "restart": "unless-stopped",
            }
        },
    }
    out = _write_artifact(
        DEPLOY_OUT_DIR / "azure-compose.yaml",
        yaml.safe_dump(compose, sort_keys=False),
    )
    console.print(f"[green]✓ Generated compose artifact:[/green] {out}")
    console.print(
        "[dim]Deploy it yourself, e.g. `az container up` or Azure Container "
        "Apps. No Azure resources were created.[/dim]"
    )


@deploy_cmd.command("kubernetes")
@click.option("--namespace", "-n", default="authy", show_default=True)
@click.option("--replicas", default=3, show_default=True)
@click.option("--image", default="authy-app:latest", show_default=True)
def kubernetes(namespace: str, replicas: int, image: str):
    """Generate Kubernetes manifests into ./deploy-out/k8s/ (no cluster calls)."""
    try:
        import yaml
    except ImportError:
        console.print("[red]✗ PyYAML is required to generate artifacts[/red]")
        raise click.exceptions.Exit(1)

    ns = {
        "apiVersion": "v1",
        "kind": "Namespace",
        "metadata": {"name": namespace},
    }
    deployment = {
        "apiVersion": "apps/v1",
        "kind": "Deployment",
        "metadata": {"name": "authy", "namespace": namespace},
        "spec": {
            "replicas": replicas,
            "selector": {"matchLabels": {"app": "authy"}},
            "template": {
                "metadata": {"labels": {"app": "authy"}},
                "spec": {
                    "containers": [
                        {
                            "name": "authy",
                            "image": image,
                            "ports": [{"containerPort": 8000}],
                        }
                    ]
                },
            },
        },
    }
    service = {
        "apiVersion": "v1",
        "kind": "Service",
        "metadata": {"name": "authy", "namespace": namespace},
        "spec": {
            "selector": {"app": "authy"},
            "ports": [{"port": 80, "targetPort": 8000}],
        },
    }

    written: List[Path] = [
        _write_artifact(DEPLOY_OUT_DIR / "k8s" / "namespace.yaml", yaml.safe_dump(ns)),
        _write_artifact(DEPLOY_OUT_DIR / "k8s" / "deployment.yaml", yaml.safe_dump(deployment)),
        _write_artifact(DEPLOY_OUT_DIR / "k8s" / "service.yaml", yaml.safe_dump(service)),
    ]
    for path in written:
        console.print(f"[green]✓ Generated manifest:[/green] {path}")
    console.print(
        "[dim]Apply yourself with `kubectl apply -f deploy-out/k8s/`. "
        "No cluster resources were created.[/dim]"
    )
