"""Passwordless authentication with passkeys / WebAuthn (CONTRACTS.md §3.1).

- Challenges are generated by the ``webauthn`` library and the
  library-generated challenge is stored and returned consistently
  (base64url).
- Per-user challenge keys per §3.1:
  ``authy:passkey:reg:{user_id}`` and
  ``authy:passkey:auth:{user_id}:{challenge}``.
- Challenges are single-use (fetched and deleted before verification).
- Credentials persist through the db settings key-value contract, so any
  §4 adapter works.
- ``webauthn`` is imported lazily (§0.9); the module imports cleanly
  without it.
"""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from urllib.parse import urlsplit

from authy_package.cache.abstract_cache import AbstractCache
from authy_package.config import AuthConfig
from authy_package.db.abstract_db import AbstractDatabase
from authy_package.errors import AuthenticationError, ConfigError

logger = logging.getLogger("authy.passwordless.passkey")

__all__ = ["PasskeyManager"]

#: §3.1 cache key schema.
REG_CHALLENGE_KEY_TEMPLATE = "authy:passkey:reg:{user_id}"
AUTH_CHALLENGE_KEY_TEMPLATE = "authy:passkey:auth:{user_id}:{challenge}"

#: Challenge TTL (WebAuthn guidance: a few minutes).
CHALLENGE_TTL_SECONDS = 300

#: db settings keys (generic kv with json values, §4).
CREDENTIAL_SETTING_TEMPLATE = "authy_passkey_credential:{credential_id}"
USER_PASSKEYS_SETTING_TEMPLATE = "authy_passkeys:{user_id}"


def _lazy_webauthn():
    """Import the webauthn library lazily with an informative error."""
    try:
        import webauthn
    except ImportError as exc:  # pragma: no cover - exercised w/o extra
        raise ImportError(
            "Passkeys require the 'webauthn' package; install authy-package "
            "with the corresponding extra"
        ) from exc
    return webauthn


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


class PasskeyManager:
    """Passkey (WebAuthn/FIDO2) registration and authentication.

    Args:
        config: Canonical :class:`AuthConfig` (rp_id, rp_name, base_url).
        db: Database adapter (§4); credentials are stored via settings kv.
        cache: Cache adapter (§3) holding the single-use challenges.
    """

    def __init__(
        self, config: AuthConfig, db: AbstractDatabase, cache: AbstractCache
    ) -> None:
        if config is None:
            raise ConfigError("PasskeyManager requires an AuthConfig")
        if db is None:
            raise ConfigError("PasskeyManager requires a database adapter")
        if cache is None:
            raise ConfigError("PasskeyManager requires a cache adapter")
        self.config = config
        self.db = db
        self.cache = cache
        self._rp_name = config.rp_name or "Authy"
        host = urlsplit(config.base_url).hostname or "localhost"
        self._rp_id = config.rp_id or host
        self._origin = config.base_url

    # -- credential storage (db settings kv) -----------------------------------

    async def _save_credential(self, record: Dict[str, Any]) -> None:
        key = CREDENTIAL_SETTING_TEMPLATE.format(credential_id=record["credential_id"])
        await self.db.set_setting(key, record)

    async def _get_credential(self, credential_id: str) -> Optional[Dict[str, Any]]:
        key = CREDENTIAL_SETTING_TEMPLATE.format(credential_id=credential_id)
        record = await self.db.get_setting(key)
        return record if isinstance(record, dict) else None

    async def _delete_credential_setting(self, credential_id: str) -> None:
        key = CREDENTIAL_SETTING_TEMPLATE.format(credential_id=credential_id)
        await self.db.set_setting(key, None)

    async def _get_user_credential_ids(self, user_id: str) -> List[str]:
        index = await self.db.get_setting(
            USER_PASSKEYS_SETTING_TEMPLATE.format(user_id=user_id)
        )
        return list(index) if isinstance(index, list) else []

    async def _set_user_credential_ids(self, user_id: str, ids: List[str]) -> None:
        await self.db.set_setting(
            USER_PASSKEYS_SETTING_TEMPLATE.format(user_id=user_id), ids
        )

    # -- registration --------------------------------------------------------------

    async def register_start(
        self,
        user_id: str,
        email: str,
        display_name: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Begin registration; returns WebAuthn creation options (JSON).

        The library-generated challenge is stored under
        ``authy:passkey:reg:{user_id}`` and returned in the options.
        """
        webauthn = _lazy_webauthn()
        from webauthn.helpers import bytes_to_base64url
        from webauthn.helpers.structs import PublicKeyCredentialDescriptor

        if not user_id or not email:
            raise ValueError("user_id and email are required")
        user = await self.db.get_user_by_id(user_id)
        if not user:
            raise ValueError("User not found")

        existing = await self.list_passkeys(user_id)
        exclude = [
            PublicKeyCredentialDescriptor(
                id=webauthn.base64url_to_bytes(cred["credential_id"])
            )
            for cred in existing
        ] or None

        options = webauthn.generate_registration_options(
            rp_id=self._rp_id,
            rp_name=self._rp_name,
            user_name=email,
            user_id=user_id.encode("utf-8"),
            user_display_name=display_name or email,
            exclude_credentials=exclude,
        )

        challenge_b64 = bytes_to_base64url(options.challenge)
        await self.cache.set_json(
            REG_CHALLENGE_KEY_TEMPLATE.format(user_id=user_id),
            {
                "challenge": challenge_b64,
                "email": email,
                "type": "registration",
                "created_at": _utcnow().isoformat(),
            },
            ttl_seconds=CHALLENGE_TTL_SECONDS,
        )
        return json.loads(webauthn.options_to_json(options))

    async def register_complete(
        self,
        user_id: str,
        credential: Any,
        device_name: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Verify the attestation against the stored challenge and persist
        the credential. The challenge is consumed (single-use)."""
        webauthn = _lazy_webauthn()
        from webauthn.helpers import bytes_to_base64url

        record = await self.cache.get_json(
            REG_CHALLENGE_KEY_TEMPLATE.format(user_id=user_id)
        )
        if record is not None:
            await self.cache.delete(REG_CHALLENGE_KEY_TEMPLATE.format(user_id=user_id))
        if not record or record.get("type") != "registration":
            raise AuthenticationError(
                "Invalid or expired registration challenge", code="passkey_challenge_invalid"
            )

        try:
            verification = webauthn.verify_registration_response(
                credential=credential,
                expected_challenge=webauthn.base64url_to_bytes(record["challenge"]),
                expected_rp_id=self._rp_id,
                expected_origin=self._origin,
            )
        except Exception as exc:
            logger.info("Passkey registration verification failed: %s", exc)
            raise AuthenticationError(
                "Registration verification failed", code="passkey_registration_failed"
            ) from exc

        credential_id_b64 = bytes_to_base64url(verification.credential_id)
        stored = {
            "id": credential_id_b64,
            "user_id": user_id,
            "credential_id": credential_id_b64,
            "public_key": bytes_to_base64url(verification.credential_public_key),
            "counter": verification.sign_count,
            "created_at": _utcnow().isoformat(),
            "last_used": None,
            "device_name": device_name,
            "transports": (credential.get("response", {}) or {}).get("transports")
            if isinstance(credential, dict)
            else None,
        }
        await self._save_credential(stored)
        ids = await self._get_user_credential_ids(user_id)
        if credential_id_b64 not in ids:
            ids.append(credential_id_b64)
        await self._set_user_credential_ids(user_id, ids)
        logger.info("Registered passkey %s for user %s", credential_id_b64, user_id)
        return stored

    # -- authentication ---------------------------------------------------------------

    async def authenticate_start(
        self,
        user_id: str,
        allow_credential_ids: Optional[List[str]] = None,
    ) -> Dict[str, Any]:
        """Begin authentication for ``user_id``; returns assertion options.

        The library-generated challenge is stored under
        ``authy:passkey:auth:{user_id}:{challenge}``.
        """
        webauthn = _lazy_webauthn()
        from webauthn.helpers import bytes_to_base64url
        from webauthn.helpers.structs import PublicKeyCredentialDescriptor

        if not user_id:
            raise ValueError("user_id is required")

        if allow_credential_ids is None:
            allow_credential_ids = await self._get_user_credential_ids(user_id)
        allow_credentials = [
            PublicKeyCredentialDescriptor(
                id=webauthn.base64url_to_bytes(credential_id)
            )
            for credential_id in allow_credential_ids
        ] or None

        options = webauthn.generate_authentication_options(
            rp_id=self._rp_id,
            allow_credentials=allow_credentials,
        )
        challenge_b64 = bytes_to_base64url(options.challenge)
        await self.cache.set_json(
            AUTH_CHALLENGE_KEY_TEMPLATE.format(user_id=user_id, challenge=challenge_b64),
            {
                "challenge": challenge_b64,
                "type": "authentication",
                "created_at": _utcnow().isoformat(),
            },
            ttl_seconds=CHALLENGE_TTL_SECONDS,
        )
        return json.loads(webauthn.options_to_json(options))

    async def authenticate_complete(
        self,
        user_id: str,
        challenge: str,
        credential: Any,
    ) -> Dict[str, Any]:
        """Verify an assertion against the per-user challenge (single-use).

        Args:
            user_id: The user the challenge was issued for.
            challenge: The base64url challenge from ``authenticate_start``.
            credential: The authenticator assertion JSON from the client.
        """
        webauthn = _lazy_webauthn()

        if not challenge or not isinstance(challenge, str):
            raise ValueError("challenge must be the base64url string issued at start")

        key = AUTH_CHALLENGE_KEY_TEMPLATE.format(user_id=user_id, challenge=challenge)
        record = await self.cache.get_json(key)
        if record is not None:
            await self.cache.delete(key)
        if not record or record.get("type") != "authentication":
            raise AuthenticationError(
                "Invalid or expired authentication challenge",
                code="passkey_challenge_invalid",
            )

        credential_id = credential.get("id") if isinstance(credential, dict) else None
        if not credential_id:
            raise ValueError("credential.id is missing")
        stored = await self._get_credential(str(credential_id))
        if not stored or stored.get("user_id") != user_id:
            raise AuthenticationError(
                "Credential not found", code="passkey_credential_not_found"
            )

        try:
            verification = webauthn.verify_authentication_response(
                credential=credential,
                expected_challenge=webauthn.base64url_to_bytes(record["challenge"]),
                expected_rp_id=self._rp_id,
                expected_origin=self._origin,
                credential_public_key=webauthn.base64url_to_bytes(stored["public_key"]),
                credential_current_sign_count=int(stored.get("counter", 0)),
            )
        except Exception as exc:
            logger.info("Passkey authentication verification failed: %s", exc)
            raise AuthenticationError(
                "Authentication verification failed", code="passkey_authentication_failed"
            ) from exc

        stored["counter"] = verification.new_sign_count
        stored["last_used"] = _utcnow().isoformat()
        await self._save_credential(stored)

        user = await self.db.get_user_by_id(user_id)
        return {
            "user": user,
            "credential_id": credential_id,
            "authenticated_at": _utcnow().isoformat(),
        }

    # -- management ---------------------------------------------------------------------

    async def list_passkeys(self, user_id: str) -> List[Dict[str, Any]]:
        """All passkey records for a user."""
        results: List[Dict[str, Any]] = []
        for credential_id in await self._get_user_credential_ids(user_id):
            record = await self._get_credential(credential_id)
            if record:
                results.append(record)
        return results

    async def delete_passkey(self, user_id: str, credential_id: str) -> bool:
        """Delete one of the user's passkeys (ownership enforced)."""
        record = await self._get_credential(credential_id)
        if not record or record.get("user_id") != user_id:
            return False
        await self._delete_credential_setting(credential_id)
        ids = await self._get_user_credential_ids(user_id)
        await self._set_user_credential_ids(
            user_id, [cid for cid in ids if cid != credential_id]
        )
        return True
